workflows:
    ios-workflow:
        name: EmotionIQ App
        environment:
            groups:
                - publishing
            vars:
                XCODE_WORKSPACE: "App.xcworkspace"
                XCODE_SCHEME: "App"
                BUNDLE_ID: "io.emotioniq.emotion.management"
                APP_STORE_APP_ID: 6502370663
                APP_DOMAIN: "riverlinesmob.site"
                APP_DISPLAY_NAME: "EmotionIQ"
                APP_VERSION: "1.0.0"
                APP_BUILD: "1"
            node: latest
        scripts:
        #   - name: Echo envs
        #     script: |
        #       echo "Private Key" $APP_STORE_CONNECT_PRIVATE_KEY
        #       echo "Key identifier" $APP_STORE_CONNECT_KEY_IDENTIFIER
        #       echo "Issuer ID" $APP_STORE_CONNECT_ISSUER_ID
        #   - name: Increment build number
        #     script: |
        #       cd $CM_BUILD_DIR/ios/App
        #         LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
        #         agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          - name: Install npm dependencies for Ionic Capacitor project
            script: |
              npm install --force
              npm run build
          - name: Cocoapods installation
            script: |
              cd ios/App && pod install
          - name: Update dependencies and copy web assets to native project
            script: |
              npx cap sync
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles
        #   - name: Build Workspace
        #     script: |
        #       cd $CM_BUILD_DIR/ios/App
        #       xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" AD_HOC_CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          - name: Build IPA
            script: |
              cd $CM_BUILD_DIR/ios/App
              xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --output-dir "$CM_BUILD_DIR/ios/App/build/ipa"
          - name: Show build directories
            script: |
              echo "Home dir" && ls -la $CM_BUILD_DIR/ios/
              echo "App dir" && ls -la $CM_BUILD_DIR/ios/App
              echo "Build dir" && ls -la $CM_BUILD_DIR/ios/App/build
              echo "IOS dir" && ls -la ios/
              echo "Developer dir" && ls -la $HOME/Library/Developer/Xcode/DerivedData/**/Build/
        artifacts:
            - ios/build/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            app_store_connect:
              api_key: $APP_STORE_CONNECT_PRIVATE_KEY
              key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
              issuer_id: $APP_STORE_CONNECT_ISSUER_ID
              submit_to_testflight: true
