workflows:
    ios-workflow:
        name: EmotionIQ App
        environment:
            groups:
                - publishing
            vars:
                XCODE_WORKSPACE: "App.xcworkspace"
                XCODE_SCHEME: "App"
                BUNDLE_ID: "io.emotioniq.emotion.management"
                APP_STORE_APP_ID: 6502370663
                APP_DOMAIN: "riverlinesmob.site"
                APP_DISPLAY_NAME: "EmotionIQ"
                APP_VERSION: "1.0.0"
                APP_BUILD: "1"
            node: latest
        scripts:
          - name: Install npm dependencies for Ionic Capacitor project
            script: |
              npm install --force
              npm run build
              npx cap sync
              npx cap update ios
          - name: Install pods
            script: |
              cd ios/App
              pod install
          - name: Echo envs
            script: |
              echo "Private Key" $APP_STORE_CONNECT_PRIVATE_KEY
              echo "Key identifier" $APP_STORE_CONNECT_KEY_IDENTIFIER
              echo "Issuer ID" $APP_STORE_CONNECT_ISSUER_ID
          - name: Increment build number
            script: |
              cd $CM_BUILD_DIR/ios/App
                LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
                agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          - name: Build ipa for distribution
            script: |
              cd $CM_BUILD_DIR/ios/App
              xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME"
          - name: Build ipa for distribution
            script: |
              cd $CM_BUILD_DIR/ios/App
                xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            app_store_connect:
              api_key: $APP_STORE_CONNECT_PRIVATE_KEY
              key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
              issuer_id: $APP_STORE_CONNECT_ISSUER_ID
              submit_to_testflight: true
