# Check out https://docs.codemagic.io/getting-started/building-an-ionic-app/ for more information
# Please review and update values in curly braces
# Remove or comment out the workflows you don't require

workflows:
    ios-workflow:
        name: Ionic App
        environment:
            groups:
                - publishing
            vars:
                XCODE_WORKSPACE: "App.xcworkspace"
                XCODE_SCHEME: "App"
                BUNDLE_ID: "io.emotioniq.emotion.management"
                APP_STORE_APP_ID: 6502370663
                APP_DOMAIN: "riverlinesmob.site"
                APP_DISPLAY_NAME: "EmotionIQ"
                APP_VERSION: "1.0.0"
                APP_BUILD: "1"
            node: latest
        scripts:
            - name: Install npm dependencies for Ionic Capacitor project
                script: |
                    npm install --force
                    npx cap sync
                    cd platforms/ios
                    pod install
                    xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            - name: iOS test
                script: |
                    xcode-project run-tests \
                      --workspace "$XCODE_WORKSPACE" \
                      --scheme "$XCODE_SCHEME" \
                      --device "iPhone 14"
                    test_report: build/ios/test/*.xml
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
        app_store_connect:
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY
            key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID
            submit_to_testflight: false
