import { Question } from "./quiz.page";

export const questions: Question[] = [
    {
        question: 'Identify which emotion is shown?',
        answer: "Admiration",
        image: "assets/quiz/faces/Admiration.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Angry",
        image: "assets/quiz/faces/Angry.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Anxiety",
        image: "assets/quiz/faces/Anxiety.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Calm",
        image: "assets/quiz/faces/Calm.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Care",
        image: "assets/quiz/faces/Care.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Confident",
        image: "assets/quiz/faces/Confident.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Contempt",
        image: "assets/quiz/faces/Contempt.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Delight",
        image: "assets/quiz/faces/Delight.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Disappointed",
        image: "assets/quiz/faces/Disappointed.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Disgust",
        image: "assets/quiz/faces/Disgust.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Easement",
        image: "assets/quiz/faces/Easement.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Ecstacy",
        image: "assets/quiz/faces/Ecstacy.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Envy",
        image: "assets/quiz/faces/Envy.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Fault",
        image: "assets/quiz/faces/Fault.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Fear",
        image: "assets/quiz/faces/Fear.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Grief",
        image: "assets/quiz/faces/Grief.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Guilt",
        image: "assets/quiz/faces/Guilt.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Happy",
        image: "assets/quiz/faces/Happy.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Hate",
        image: "assets/quiz/faces/Hate.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Hope",
        image: "assets/quiz/faces/Hope.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Interest",
        image: "assets/quiz/faces/Interest.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Joy",
        image: "assets/quiz/faces/Joy.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Lonely",
        image: "assets/quiz/faces/Lonely.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Love",
        image: "assets/quiz/faces/Love.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Pity",
        image: "assets/quiz/faces/Pity.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Sad",
        image: "assets/quiz/faces/Sad.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Shame",
        image: "assets/quiz/faces/Shame.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Surprised",
        image: "assets/quiz/faces/Surprised.png",
        choices: [],
        hintUsed: false,
    },
    {
        question: 'Identify which emotion is shown?',
        answer: "Uncertainty",
        image: "assets/quiz/faces/Uncertainty.png",
        choices: [],
        hintUsed: false,
    }
]